[workspace.dependencies]
approx = "0.5.1"
eyre = "0.6.12"
itertools = "0.14.0"
num-traits = "0.2.19"
rand = "0.9.1"
rand_chacha = "0.9.0"

[workspace]
members = [
    "quadtree",
    "visualize"
]
resolver = "3"