[package]
name = "visualize"
version = "0.1.0"
edition = "2024"

[dependencies]
quadtree = {path = "../quadtree", features=["nannou"]}
rand.workspace = true
eyre.workspace = true
nannou.workspace = true
nannou_egui.workspace = true
